### ISSUE TITLE
Test individual deployment types

### ISSUE THREAD

**Issue by chr15m** [piku/piku#373]
The idea is to start a [service container](https://docs.github.com/en/actions/using-containerized-services/about-service-containers) in GitHub actions that will run `piku.py`. Then the tests would connect to it over SSH to deploy different types of apps using the client script. It would push example code and then make a web request to check the service has started correctly. This would be a full e2e test of the major feature of Piku (except for SSL cert provision).

Just putting this here to remind myself. Might be better to do this on the `piku-bootstrap` repo, not sure.

**Comment by chr15m** [comment]
Example action that sets up a service called `target` which can be SSH'ed in to.

```
name: Piku e2e testing

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      target:
        image: ubuntu:latest
        ports:
          - 22
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up SSH in target container
      run: |
        docker exec ${{ job.services.target.id }} apt-get update
        docker exec ${{ job.services.target.id }} apt-get install -y openssh-server
        docker exec ${{ job.services.target.id }} service ssh start
        docker exec ${{ job.services.target.id }} useradd -m testuser
        docker exec ${{ job.services.target.id }} bash -c 'echo "testuser:password" | chpasswd'
```
